# Cell2Structure project configuration

# define the BBBC021 csv files
[[BBC021_CSV]]
type = "compounds"
url = "https://data.broadinstitute.org/bbbc/BBBC021/BBBC021_v1_compound.csv"
file = "BBBC021_v1_compound.csv"

[[BBC021_CSV]]
type = "images"
url = "https://data.broadinstitute.org/bbbc/BBBC021/BBBC021_v1_image.csv"
file = "BBBC021_v1_image.csv"

[[BBC021_CSV]]
type = "moas"
url = "https://data.broadinstitute.org/bbbc/BBBC021/BBBC021_v1_moa.csv"
file = "BBBC021_v1_moa.csv"

[[BBC021_CSV]]
type = "moas_enhanced"
file = "BBBC021_v1_compound_smiles_moa.xlsx"

# additional structures
[structures]
DMSO = "CS(=O)C"

# file name of the final dataset
[final_dataset]
file_original = "BBBC021_final_original_dataset.csv"
file_enhanced = "BBBC021_final_enhanced_dataset.csv"

# paramteres for generation of Morgan chemical fingerprints
[Moragen_FP_params]
radius = 2
size = 2048